title: "Peter H. Vartanian"
description: "Notes, experiments, and working ideas in geo-technology (and beyond)."
url: "https://petervartanian.xyz"
baseurl: ""

author:
  name: "Peter H. Vartanian"
  email: "contact@petervartanian.xyz"

github_username: petervartanian

theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

feed:
  path: feed.xml

lang: en-US
timezone: America/New_York

og_image: /assets/img/card-default.jpg

navigation:
  - title: "about"
    url: /
  - title: "projects"
    url: /projects
  - title: "media"
    url: /media
  - title: "cv"
    url: /cv
  - title: "contact"
    url: /contact

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
